// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqMXo7KbVuTbw_rC3wuTHMAV4eUCfcXN4',
    appId: '1:728487810402:android:0913fb42fc8a9663ffc83b',
    messagingSenderId: '728487810402',
    projectId: 'hmu-time',
    storageBucket: 'hmu-time.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPMEVqvBKxf0POB-HU9rlCx3NXT3vqC5Y',
    appId: '1:728487810402:ios:226492480f1a7a1effc83b',
    messagingSenderId: '728487810402',
    projectId: 'hmu-time',
    storageBucket: 'hmu-time.firebasestorage.app',
    iosBundleId: 'com.example.hmuTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPMEVqvBKxf0POB-HU9rlCx3NXT3vqC5Y',
    appId: '1:728487810402:ios:226492480f1a7a1effc83b',
    messagingSenderId: '728487810402',
    projectId: 'hmu-time',
    storageBucket: 'hmu-time.firebasestorage.app',
    iosBundleId: 'com.example.hmuTime',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBH7TcIhSU84-OjmgMKNuHqMQ_tZcyS3UE',
    appId: '1:728487810402:web:49bd9742adc9f74fffc83b',
    messagingSenderId: '728487810402',
    projectId: 'hmu-time',
    authDomain: 'hmu-time.firebaseapp.com',
    storageBucket: 'hmu-time.firebasestorage.app',
  );

}